export const types = {
	CHANGE_PATH: 'CHANGE_PATH',
	FETCH_CURRENT_IMAGE_REQUEST: 'FETCH_CURRENT_IMAGE_REQUEST',
	FETCH_CURRENT_IMAGE_SUCCESS: 'FETCH_CURRENT_IMAGE_SUCCESS',
	FETCH_CURRENT_IMAGE_ERROR: 'FETCH_CURRENT_IMAGE_ERROR',
	FETCH_IMAGE_LIST_REQUEST: 'FETCH_IMAGE_LIST_REQUEST',
	FETCH_IMAGE_LIST_SUCCESS: 'FETCH_IMAGE_LIST_SUCCESS',
	FETCH_IMAGE_LIST_ERROR: 'FETCH_IMAGE_LIST_ERROR',
	FETCH_DEVICE_LIST_REQUEST: 'FETCH_DEVICE_LIST_REQUEST',
	FETCH_DEVICE_LIST_SUCCESS: 'FETCH_DEVICE_LIST_SUCCESS',
	FETCH_DEVICE_LIST_ERROR: 'FETCH_DEVICE_LIST_ERROR',
	SET_CURRENT_DEVICE: 'SET_CURRENT_DEVICE',
	SET_SELECTED_IMAGE: 'SET_SELECTED_IMAGE'
};
